- name: create ec2 instance
  hosts: local
  connection: local
  vars:
    ami_id: "ami-0220d79f3f480ecf5"
    sg_id: "sg-00234e667183faf3a"
    zone_id: "Z0209787199P76DBHQQAW"
    intances:
    - mongodb
  tasks:
  - name: crate ec2-intance
    amazon.aws.ec2_instance:
      name: "{ item }"
      region: us-east-1 
      instance_type: t3.micro
      security_groups: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      state: running
      tags:
        name: "{{ item }}"
    loop: "{{ intances }}"
    register: ec2_output

  - name: print ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"
      
   

