-  name: variables as tasks
   hosts: local
   connection: local
   vars:
     COURSE: Devops
     DURATION: 120 120HRS
     TRAINER: shiva kunmar
   tasks:
   - name: print course 
     vars:
     COURSE: Azure
     ansible.builtin.debug:
        msg: "Course name is: {{ COURSE }}, Duration is: {{ DURATION }}, Trainer is: {{ TRAINER }}"
  
     

   